# Delay period
delaySeconds: 10

# Resources to delay
resources:
  - configmaps
  # - jobs
  # - persistentvolumeclaims
  # - persistentvolumes
  # - pods
  # - serviceaccounts

# Delay Server image (delay.py)
image: python:3.14-slim

service:
  type: ClusterIP
  port: 443

ingress:
  enabled: false
  tls: false
  hosts: []
