apiVersion: v1
kind: PersistentVolume
metadata:
  name: funnel-worker-pv-{{`{{.TaskId}}`}}
  labels:
    app: funnel
    taskId: {{`{{.TaskId}}`}}
spec:
  # Using an empty string for storageClassName helps avoid conflicts 
  # with the 'standard' provisioner while satisfying the manual link.
  storageClassName: "manual" 
  capacity:
    storage: "10Mi"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  # hostPath is the simplest "benign" volume type for kind
  hostPath:
    path: "/tmp/funnel-{{`{{.TaskId}}`}}"
    type: DirectoryOrCreate
  claimRef:
    namespace: {{`{{.Namespace}}`}}
    name: funnel-worker-pvc-{{`{{.TaskId}}`}}
