apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: funnel-worker-pvc-{{`{{.TaskId}}`}}
  namespace: {{`{{.Namespace}}`}}
  labels:
    app: funnel
    taskId: {{`{{.TaskId}}`}}
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  # Explicitly bind to the PV created by Funnel
  volumeName: funnel-worker-pv-{{`{{.TaskId}}`}}
